version: '3.8'
networks:
  app-tier:
    driver: bridge
services:
  backend:
      build: ./Api
      environment:
        - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
        - CASSANDRA_KEYSPACE=cassandra_keyspace   
        - CASSANDRA_USERNAME=cassandra
        - CASSANDRA_PASSWORD=cassandra 
      depends_on:
        - cassandra-node1
      ports:
        - "3000:3000"
      networks:
      - app-tier
  cassandra-node1:
    container_name: cassandra-node-1
    image: bitnami/cassandra:4.0.4
    volumes:
      - ./cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra 
    networks:
      - app-tier

  cassandra-node2:
    container_name: cassandra-node-2
    image: bitnami/cassandra:4.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra 
    networks:
      - app-tier

  cassandra-node3:
    container_name: cassandra-node-3
    image: bitnami/cassandra:4.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra 
    networks:
      - app-tier